# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Rcwybtz' do
  use_frameworks!

  pod 'SideMenu'

  target 'RcwybtzTests' do
    inherit! :search_paths

    # Pods for testing
  end

end
